# Generated by Django 3.2.7 on 2022-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            db_table='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, unique_together='email', verbose_name='email and subject')),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]

