# Generated by Django 3.2.7 on 2023-02-20 14:15

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Rename field 'cagtegory' to 'category' in the 'Product' model
        migrations.RenameField(
            model_name='product',
            old_name='cagtegory',
            new_name='category',
        ),

        # Remove the 'tags' field from the 'Product' model
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),

        # Add a new 'TaggedItem' through model to enable many-to-many relationship between 'Product' and 'Tag' models
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag', related_name='products', blank=True),
        ),
    ]

