# Generated by Django 3.2.7 on 2023-03-14 14:48

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_cover_image'), # assuming there is a migration 0007 that creates the Vendor.cover_image field
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='core.product'),
        ),
    ]

