# Generated by Django 3.2.7 on 2022-10-18 15:46

from django.db import migrations
import taggit.managers as taggit_managers


def add_taggable_manager_to_product(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    db_alias = schema_editor.connection.alias
    Product.objects.using(db_alias).update(tags=taggit_managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'))

