# Generated by Django 3.2.7 on 2022-11-16 19:08

from django.db import migrations
import shortuuid

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_pid_cartorder_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, null=True, blank=True, prefix='SKU'),
        ),
    ]

